static const char *font[][11] =
  {
    { "8 8 2 1", "X c yellow", ". c black",
      "........",
      "..XXXX..",
      ".X..XX..",
      ".X......",
      "..XXXX..",
      "......X.",
      ".XX...X.",
      "X..XXX.."
    },
    { "8 8 2 1", "X c yellow", ". c black",
      "........",
      "..XXXX..",
      "..XX..X.",
      "......X.",
      "..XXXX..",
      ".X......",
      ".X...XX.",
      "..XXX..X"
    },
    { "8 8 2 1", "X c cyan", ". c black",
      "..X.X...",
      "...X....",
      ".XX.XX..",
      ".XX.XX..",
      "........",
      ".XX.XX..",
      ".XX.XX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "X......X",
      "X......X",
      "XXXXXXXX",
      "X......X",
      "X......X",
      "X......X",
      "XXXXXXXX",
      "X......X"
    },
    { "8 8 2 1", "X c cyan", ". c black",
      "........",
      "........",
      "...X....",
      "...X....",
      "...X....",
      "...X....",
      "X..X..X.",
      ".XXXXX.."
    },
    { "8 8 2 1", "X c cyan", ". c black",
      "........",
      "XXXXXX..",
      "......X.",
      ".XXXXX..",
      "X.......",
      ".XXXXX..",
      "......X.",
      "XXXXXX.."
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "X..X..X.",
      "X.X.X.X.",
      "X.X.X.X.",
      "X.X.X.X.",
      "X.X.X.X.",
      "X.X.X.X.",
      ".X...X.."
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      ".XXX....",
      "XXXXX...",
      "XXXXX...",
      "XXXXX...",
      ".XXX...."
    },
    { "8 8 2 1", "X c yellow", ". c black",
      "...X....",
      "..XXX...",
      ".XXXXX..",
      ".XXXXX..",
      ".XXXXX..",
      ".XXXXX..",
      "XXXXXXX.",
      "..X....."
    },
    { "8 8 2 1", "X c green", ". c black",
      "XX..XX..",
      "........",
      ".XXXX...",
      "XX..XX..",
      "XXXXXX..",
      "XX......",
      ".XXXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XXX.....",
      "........",
      ".XXXX...",
      "XX..XX..",
      "XXXXXX..",
      "XX......",
      ".XXXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XX..XX..",
      "........",
      ".XXX....",
      "..XX....",
      "..XX....",
      "..XX....",
      ".XXXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      ".XXXXX..",
      "XX...XX.",
      "..XXX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "..XXXX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XXX.....",
      "........",
      ".XXX....",
      "..XX....",
      "..XX....",
      "..XX....",
      ".XXXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XX...XX.",
      "..XXX...",
      ".XX.XX..",
      "XX...XX.",
      "XXXXXXX.",
      "XX...XX.",
      "XX...XX.",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX....",
      "..XX....",
      "........",
      ".XXXX...",
      "XX..XX..",
      "XXXXXX..",
      "XX..XX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XXX..",
      "........",
      "XXXXXX..",
      ".XX.....",
      ".XXXX...",
      ".XX.....",
      "XXXXXX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      ".XXXXXXX",
      "....XX..",
      ".XXXXXXX",
      "XX..XX..",
      ".XXXXXXX",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XXXXX.",
      ".XX.XX..",
      "XX..XX..",
      "XXXXXXX.",
      "XX..XX..",
      "XX..XX..",
      "XX..XXX.",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      ".XXXX...",
      "XX..XX..",
      "........",
      ".XXXX...",
      "XX..XX..",
      "XX..XX..",
      ".XXXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "XX..XX..",
      "........",
      ".XXXX...",
      "XX..XX..",
      "XX..XX..",
      ".XXXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "XXX.....",
      "........",
      ".XXXX...",
      "XX..XX..",
      "XX..XX..",
      ".XXXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      ".XXXX...",
      "XX..XX..",
      "........",
      "XX..XX..",
      "XX..XX..",
      "XX..XX..",
      ".XXXXXX.",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "XXX.....",
      "........",
      "XX..XX..",
      "XX..XX..",
      "XX..XX..",
      ".XXXXXX.",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "XX..XX..",
      "........",
      "XX..XX..",
      "XX..XX..",
      ".XXXXX..",
      "....XX..",
      "XXXXX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "XX....XX",
      "...XX...",
      "..XXXX..",
      ".XX..XX.",
      ".XX..XX.",
      "..XXXX..",
      "...XX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XX..XX..",
      "........",
      "XX..XX..",
      "XX..XX..",
      "XX..XX..",
      "XX..XX..",
      ".XXXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      ".XXXXXX.",
      "XX......",
      "XX......",
      ".XXXXXX.",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XXX...",
      ".XX.XX..",
      ".XX..X..",
      "XXXX....",
      ".XX.....",
      "XXX..XX.",
      "XXXXXX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XX..XX..",
      "XX..XX..",
      ".XXXX...",
      "XXXXXX..",
      "..XX....",
      "XXXXXX..",
      "..XX....",
      "..XX...."
    },
    { "8 8 2 1", "X c green", ". c black",
      "XXXXX...",
      "XX..XX..",
      "XX..XX..",
      "XXXXX.X.",
      "XX...XX.",
      "XX..XXXX",
      "XX...XX.",
      "XX...XXX"
    },
    { "8 8 2 1", "X c green", ". c black",
      "....XXX.",
      "...XX.XX",
      "...XX...",
      "..XXXX..",
      "...XX...",
      "...XX...",
      "XX.XX...",
      ".XXX...."
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XXX..",
      "........",
      ".XXXX...",
      "....XX..",
      ".XXXXX..",
      "XX..XX..",
      ".XXXXXX.",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XXX...",
      "........",
      ".XXX....",
      "..XX....",
      "..XX....",
      "..XX....",
      ".XXXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "...XXX..",
      "........",
      ".XXXX...",
      "XX..XX..",
      "XX..XX..",
      ".XXXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "...XXX..",
      "........",
      "XX..XX..",
      "XX..XX..",
      "XX..XX..",
      ".XXXXXX.",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "XXXXX...",
      "........",
      "XXXXX...",
      "XX..XX..",
      "XX..XX..",
      "XX..XX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XXXXXX..",
      "........",
      "XX..XX..",
      "XXX.XX..",
      "XXXXXX..",
      "XX.XXX..",
      "XX..XX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XXXX..",
      ".XX.XX..",
      ".XX.XX..",
      "..XXXXX.",
      "........",
      ".XXXXXX.",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XXX...",
      ".XX.XX..",
      ".XX.XX..",
      "..XXX...",
      "........",
      ".XXXXX..",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX....",
      "........",
      "..XX....",
      ".XX.....",
      "XX......",
      "XX..XX..",
      ".XXXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      "XXXXXX..",
      "XX......",
      "XX......",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      "XXXXXX..",
      "....XX..",
      "....XX..",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XX....XX",
      "XX...XX.",
      "XX..XX..",
      "XX.XXXX.",
      "..XX..XX",
      ".XX..XX.",
      "XX..XX..",
      "....XXXX"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XX....XX",
      "XX...XX.",
      "XX..XX..",
      "XX.XX.XX",
      "..XX.XXX",
      ".XX.XXXX",
      "XX..XXXX",
      "......XX"
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "........",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "..XX..XX",
      ".XX..XX.",
      "XX..XX..",
      ".XX..XX.",
      "..XX..XX",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "XX..XX..",
      ".XX..XX.",
      "..XX..XX",
      ".XX..XX.",
      "XX..XX..",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..X...X.",
      "X...X...",
      "..X...X.",
      "X...X...",
      "..X...X.",
      "X...X...",
      "..X...X.",
      "X...X..."
    },
    { "8 8 2 1", "X c green", ". c black",
      ".X.X.X.X",
      "X.X.X.X.",
      ".X.X.X.X",
      "X.X.X.X.",
      ".X.X.X.X",
      "X.X.X.X.",
      ".X.X.X.X",
      "X.X.X.X."
    },
    { "8 8 2 1", "X c green", ". c black",
      "XX.XX.XX",
      ".XXX.XXX",
      "XX.XX.XX",
      "XXX.XXX.",
      "XX.XX.XX",
      ".XXX.XXX",
      "XX.XX.XX",
      "XXX.XXX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "XXXXX...",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "XXXXX...",
      "...XX...",
      "XXXXX...",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "XXXX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      "........",
      "XXXXXXX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "XXXXX...",
      "...XX...",
      "XXXXX...",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "XXXX.XX.",
      ".....XX.",
      "XXXX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "XXXXXXX.",
      ".....XX.",
      "XXXX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "XXXX.XX.",
      ".....XX.",
      "XXXXXXX.",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "XXXXXXX.",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "XXXXX...",
      "...XX...",
      "XXXXX...",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      "........",
      "XXXXX...",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XXXXX",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "XXXXXXXX",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      "........",
      "XXXXXXXX",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XXXXX",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "XXXXXXXX",
      "........",
      "........",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "XXXXXXXX",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "...XXXXX",
      "...XX...",
      "...XXXXX",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XXX",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XXX",
      "..XX....",
      "..XXXXXX",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "..XXXXXX",
      "..XX....",
      "..XX.XXX",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "XXXX.XXX",
      "........",
      "XXXXXXXX",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "XXXXXXXX",
      "........",
      "XXXX.XXX",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XXX",
      "..XX....",
      "..XX.XXX",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "XXXXXXXX",
      "........",
      "XXXXXXXX",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "XXXX.XXX",
      "........",
      "XXXX.XXX",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "XXXXXXXX",
      "........",
      "XXXXXXXX",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "XXXXXXXX",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "XXXXXXXX",
      "........",
      "XXXXXXXX",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      "........",
      "XXXXXXXX",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XXXXXX",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "...XXXXX",
      "...XX...",
      "...XXXXX",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "...XXXXX",
      "...XX...",
      "...XXXXX",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      "........",
      "..XXXXXX",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX.",
      "XXXXXXXX",
      "..XX.XX.",
      "..XX.XX.",
      "..XX.XX."
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "XXXXXXXX",
      "...XX...",
      "XXXXXXXX",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "XXXXX...",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      "........",
      "...XXXXX",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "XXXXXXXX",
      "XXXXXXXX",
      "XXXXXXXX",
      "XXXXXXXX",
      "XXXXXXXX",
      "XXXXXXXX",
      "XXXXXXXX",
      "XXXXXXXX"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      "........",
      "XXXXXXXX",
      "XXXXXXXX",
      "XXXXXXXX",
      "XXXXXXXX"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XXXX....",
      "XXXX....",
      "XXXX....",
      "XXXX....",
      "XXXX....",
      "XXXX....",
      "XXXX....",
      "XXXX...."
    },
    { "8 8 2 1", "X c green", ". c black",
      "....XXXX",
      "....XXXX",
      "....XXXX",
      "....XXXX",
      "....XXXX",
      "....XXXX",
      "....XXXX",
      "....XXXX"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XXXXXXXX",
      "XXXXXXXX",
      "XXXXXXXX",
      "XXXXXXXX",
      "........",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      ".XXX.XX.",
      "XX.XXX..",
      "XX..X...",
      "XX.XXX..",
      ".XXX.XX.",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      ".XXXX...",
      "XX..XX..",
      "XXXXX...",
      "XX..XX..",
      "XXXXX...",
      "XX......",
      "XX......"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "XXXXXX..",
      "XX..XX..",
      "XX......",
      "XX......",
      "XX......",
      "XX......",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "XXXXXXX.",
      ".XX.XX..",
      ".XX.XX..",
      ".XX.XX..",
      ".XX.XX..",
      ".XX.XX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XXXXXX..",
      "XX..XX..",
      ".XX.....",
      "..XX....",
      ".XX.....",
      "XX..XX..",
      "XXXXXX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      ".XXXXXX.",
      "XX.XX...",
      "XX.XX...",
      "XX.XX...",
      ".XXX....",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      ".XX..XX.",
      ".XX..XX.",
      ".XX..XX.",
      ".XX..XX.",
      ".XXXXX..",
      ".XX.....",
      "XX......"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      ".XXX.XX.",
      "XX.XXX..",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "XXXXXX..",
      "..XX....",
      ".XXXX...",
      "XX..XX..",
      "XX..XX..",
      ".XXXX...",
      "..XX....",
      "XXXXXX.."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XXX...",
      ".XX.XX..",
      "XX...XX.",
      "XXXXXXX.",
      "XX...XX.",
      ".XX.XX..",
      "..XXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XXX...",
      ".XX.XX..",
      "XX...XX.",
      "XX...XX.",
      ".XX.XX..",
      ".XX.XX..",
      "XXX.XXX.",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XXX..",
      "..XX....",
      "...XX...",
      ".XXXXX..",
      "XX..XX..",
      "XX..XX..",
      ".XXXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      ".XXXXXX.",
      "XX.XX.XX",
      "XX.XX.XX",
      ".XXXXXX.",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      ".....XX.",
      "....XX..",
      ".XXXXXX.",
      "XX.XX.XX",
      "XX.XX.XX",
      ".XXXXXX.",
      ".XX.....",
      "XX......"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XXX...",
      ".XX.....",
      "XX......",
      "XXXXX...",
      "XX......",
      ".XX.....",
      "..XXX...",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      ".XXXX...",
      "XX..XX..",
      "XX..XX..",
      "XX..XX..",
      "XX..XX..",
      "XX..XX..",
      "XX..XX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "XXXXXX..",
      "........",
      "XXXXXX..",
      "........",
      "XXXXXX..",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX....",
      "..XX....",
      "XXXXXX..",
      "..XX....",
      "..XX....",
      "........",
      "XXXXXX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      ".XX.....",
      "..XX....",
      "...XX...",
      "..XX....",
      ".XX.....",
      "........",
      "XXXXXX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "..XX....",
      ".XX.....",
      "..XX....",
      "...XX...",
      "........",
      "XXXXXX..",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "....XXX.",
      "...XX.XX",
      "...XX.XX",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX..."
    },
    { "8 8 2 1", "X c green", ". c black",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "...XX...",
      "XX.XX...",
      "XX.XX...",
      ".XXX...."
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XX....",
      "..XX....",
      "........",
      "XXXXXX..",
      "........",
      "..XX....",
      "..XX....",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      ".XXX.XX.",
      "XX.XXX..",
      "........",
      ".XXX.XX.",
      "XX.XXX..",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "..XXX...",
      ".XX.XX..",
      ".XX.XX..",
      "..XXX...",
      "........",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      "...XX...",
      "...XX...",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      "........",
      "...XX...",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "....XXXX",
      "....XX..",
      "....XX..",
      "....XX..",
      "XXX.XX..",
      ".XX.XX..",
      "..XXXX..",
      "...XXX.."
    },
    { "8 8 2 1", "X c green", ". c black",
      ".XXXX...",
      ".XX.XX..",
      ".XX.XX..",
      ".XX.XX..",
      ".XX.XX..",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      ".XXX....",
      "...XX...",
      "..XX....",
      ".XX.....",
      ".XXXX...",
      "........",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "..XXXX..",
      "..XXXX..",
      "..XXXX..",
      "..XXXX..",
      "........",
      "........"
    },
    { "8 8 2 1", "X c green", ". c black",
      "........",
      "........",
      "........",
      "........",
      "........",
      "........",
      "........",
      "........"
  }
};
static int fontlen = 128;
