/*********************************************************************
 * Name:      	main.cpp
 * Purpose:   	Implements simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:    
 * Created:   
 * Copyright: 
 * License:   	wxWidgets license (www.wxwidgets.org)
 * 
 * Notes:		Note that all GUI creation code is implemented in
 * 				gui.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "wxmain.h"

// initialize the application
IMPLEMENT_APP(MainApp);

////////////////////////////////////////////////////////////////////////////////
// application class implementation 
////////////////////////////////////////////////////////////////////////////////

bool MainApp::OnInit()
{
	SetTopWindow( new MainFrame( NULL ) );
	GetTopWindow()->Show();
	
	// true = enter the main loop
	return true;
}

////////////////////////////////////////////////////////////////////////////////
// main application frame implementation 
////////////////////////////////////////////////////////////////////////////////

MainFrame::MainFrame(wxWindow *parent) : MainFrameBase( parent )
{
    #include "willychr.h"
    std::vector<wxBitmap> fontBitmaps;
    
    for(int i=0; i<fontlen; i++)
    {
        wxBitmap bitmap(font[i]);
        this->font.push_back(bitmap);
        this->fontScaled.push_back(wxBitmap(bitmap.ConvertToImage().Scale(24,24,wxIMAGE_QUALITY_NORMAL)));
    }
}

MainFrame::~MainFrame()
{
}

void MainFrame::OnCloseFrame(wxCloseEvent& event)
{
	Destroy();
}

void MainFrame::OnExitClick(wxCommandEvent& event)
{
	Destroy();
}

void MainFrame::OnAbortGame(wxCommandEvent& event)
{
	Destroy();
}

void MainFrame::OnKeyDown(wxKeyEvent& event)
{
    newCommand=command[(unsigned char)event.GetKeyCode()];
}

void MainFrame::onPaint( wxPaintEvent& event ) 
{   int scale=spritesize.GetValue();

    wxClientDC draw(m_panel1);
    draw.DrawBitmap(fontScaled[1],3*scale,5*scale);
}

void MainFrame::onSpriteSizeUpdate( wxScrollEvent& event )
{   int scale=spritesize.GetValue();

    for(int i=0; i<fontlen; i++)
    {
        this->fontScaled[i]=wxBitmap(font[i].ConvertToImage().Scale(scale,scale,wxIMAGE_QUALITY_NORMAL));
    }
}

void MainFrame::onSpeedUpdate( wxScrollEvent& event ) 
{ event.Skip(); 
}